Lang = {
    ["EN"] = {
      ["success"]           ="You gave the goods to the buyer, and when you sell, leave no place that will leave the money here and someone else can get the money...",
      ["dony_have"]           ="You dont have enough '",
      ["no_police"]           ="Not enought police",
      ["other_action"]           ="Someone else is currently trading",
      ["take_money"]           ="$' you got",
      ["cancelled"]           ="You canceled",
      ["tooke_money"]           ="The buyer left the money",
      ["delivery_now"]           ="Buyer is on delivery now",
      ["take_money1"]           ="Take the money",
      ["cancel"]           ="Cancel",
      ["how_many"]           ="How many pieces do you want to sell",
      ["please_value1"]           ="Please with '1''",
      ["please_value2"]           ="' enter a value between",
      ["Invalid_value"]           ="Invalid value",
      ["interact"]           ="Interact",
    },
    ["Custom"] = {
    },
    ["TR"] = {
      ["success"]           ="You gave the goods to the buyer, and when you sell, leave no place that will leave the money here and someone else can get the money...",
      ["dony_have"]           ="You dont have enough '",
      ["no_police"]           ="Not enought police",
      ["other_action"]           ="Someone else is currently trading",
      ["take_money"]           ="$' you got",
      ["cancelled"]           ="You canceled",
      ["tooke_money"]           ="The buyer left the money",
      ["delivery_now"]           ="Buyer is on delivery now",
      ["take_money1"]           ="Take the money",
      ["cancel"]           ="Cancel",
      ["how_many"]           ="How many pieces do you want to sell",
      ["please_value1"]           ="Please with '1''",
      ["please_value2"]           ="' enter a value between",
      ["Invalid_value"]           ="Invalid value",
      ["interact"]           ="Interact",
    },
}

